-- AUTO-GENERADO por etl_pokedex.py
-- Truncar y re-sembrar master_pokemon
TRUNCATE TABLE public.master_pokemon RESTART IDENTITY CASCADE;

INSERT INTO public.master_pokemon
  (id_interno_gba, nombre_en, nombre_es, tipo_1, tipo_2,
   generacion, creado_en)
VALUES
  (1, 'Bulbasaur', 'Bulbasaur', 'Planta', 'Veneno', 1, now()),
  (2, 'Ivysaur', 'Ivysaur', 'Planta', 'Veneno', 1, now()),
  (3, 'Venusaur', 'Venusaur', 'Planta', 'Veneno', 1, now()),
  (4, 'Charmander', 'Charmander', 'Fuego', NULL, 1, now()),
  (5, 'Charmeleon', 'Charmeleon', 'Fuego', NULL, 1, now()),
  (6, 'Charizard', 'Charizard', 'Fuego', 'Volador', 1, now()),
  (7, 'Squirtle', 'Squirtle', 'Agua', NULL, 1, now()),
  (8, 'Wartortle', 'Wartortle', 'Agua', NULL, 1, now()),
  (9, 'Blastoise', 'Blastoise', 'Agua', NULL, 1, now()),
  (10, 'Caterpie', 'Caterpie', 'Bicho', NULL, 1, now()),
  (11, 'Metapod', 'Metapod', 'Bicho', NULL, 1, now()),
  (12, 'Butterfree', 'Butterfree', 'Bicho', 'Volador', 1, now()),
  (13, 'Weedle', 'Weedle', 'Bicho', 'Veneno', 1, now()),
  (14, 'Kakuna', 'Kakuna', 'Bicho', 'Veneno', 1, now()),
  (15, 'Beedrill', 'Beedrill', 'Bicho', 'Veneno', 1, now()),
  (16, 'Pidgey', 'Pidgey', 'Normal', 'Volador', 1, now()),
  (17, 'Pidgeotto', 'Pidgeotto', 'Normal', 'Volador', 1, now()),
  (18, 'Pidgeot', 'Pidgeot', 'Normal', 'Volador', 1, now()),
  (19, 'Rattata', 'Rattata', 'Normal', NULL, 1, now()),
  (20, 'Raticate', 'Raticate', 'Normal', NULL, 1, now()),
  (21, 'Spearow', 'Spearow', 'Normal', 'Volador', 1, now()),
  (22, 'Fearow', 'Fearow', 'Normal', 'Volador', 1, now()),
  (23, 'Ekans', 'Ekans', 'Veneno', NULL, 1, now()),
  (24, 'Arbok', 'Arbok', 'Veneno', 'Siniestro', 1, now()),
  (25, 'Pikachu', 'Pikachu', 'Eléctrico', NULL, 1, now()),
  (26, 'Raichu', 'Raichu', 'Eléctrico', NULL, 1, now()),
  (27, 'Sandshrew', 'Sandshrew', 'Tierra', NULL, 1, now()),
  (28, 'Sandslash', 'Sandslash', 'Tierra', NULL, 1, now()),
  (29, 'Nidoran F', 'Nidoran♀', 'Veneno', NULL, 1, now()),
  (30, 'Nidorina', 'Nidorina', 'Veneno', NULL, 1, now()),
  (31, 'Nidoqueen', 'Nidoqueen', 'Veneno', 'Tierra', 1, now()),
  (32, 'Nidoran M', 'Nidoran♂', 'Veneno', NULL, 1, now()),
  (33, 'Nidorino', 'Nidorino', 'Veneno', NULL, 1, now()),
  (34, 'Nidoking', 'Nidoking', 'Veneno', 'Tierra', 1, now()),
  (35, 'Clefairy', 'Clefairy', 'Hada', NULL, 1, now()),
  (36, 'Clefable', 'Clefable', 'Hada', NULL, 1, now()),
  (37, 'Vulpix', 'Vulpix', 'Fuego', NULL, 1, now()),
  (38, 'Ninetales', 'Ninetales', 'Fuego', NULL, 1, now()),
  (39, 'Jigglypuff', 'Jigglypuff', 'Normal', 'Hada', 1, now()),
  (40, 'Wigglytuff', 'Wigglytuff', 'Normal', 'Hada', 1, now()),
  (41, 'Zubat', 'Zubat', 'Veneno', 'Volador', 1, now()),
  (42, 'Golbat', 'Golbat', 'Veneno', 'Volador', 1, now()),
  (43, 'Oddish', 'Oddish', 'Planta', 'Veneno', 1, now()),
  (44, 'Gloom', 'Gloom', 'Planta', 'Veneno', 1, now()),
  (45, 'Vileplume', 'Vileplume', 'Planta', 'Veneno', 1, now()),
  (46, 'Paras', 'Paras', 'Bicho', 'Planta', 1, now()),
  (47, 'Parasect', 'Parasect', 'Bicho', 'Fantasma', 1, now()),
  (48, 'Venonat', 'Venonat', 'Bicho', 'Veneno', 1, now()),
  (49, 'Venomoth', 'Venomoth', 'Bicho', 'Veneno', 1, now()),
  (50, 'Diglett', 'Diglett', 'Tierra', NULL, 1, now()),
  (51, 'Dugtrio', 'Dugtrio', 'Tierra', NULL, 1, now()),
  (52, 'Meowth', 'Meowth', 'Normal', NULL, 1, now()),
  (53, 'Persian', 'Persian', 'Normal', NULL, 1, now()),
  (54, 'Psyduck', 'Psyduck', 'Agua', NULL, 1, now()),
  (55, 'Golduck', 'Golduck', 'Agua', 'Psíquico', 1, now()),
  (56, 'Mankey', 'Mankey', 'Lucha', NULL, 1, now()),
  (57, 'Primeape', 'Primeape', 'Lucha', NULL, 1, now()),
  (58, 'Growlithe', 'Growlithe', 'Fuego', NULL, 1, now()),
  (59, 'Arcanine', 'Arcanine', 'Fuego', NULL, 1, now()),
  (60, 'Poliwag', 'Poliwag', 'Agua', NULL, 1, now()),
  (61, 'Poliwhirl', 'Poliwhirl', 'Agua', NULL, 1, now()),
  (62, 'Poliwrath', 'Poliwrath', 'Agua', 'Lucha', 1, now()),
  (63, 'Abra', 'Abra', 'Psíquico', NULL, 1, now()),
  (64, 'Kadabra', 'Kadabra', 'Psíquico', NULL, 1, now()),
  (65, 'Alakazam', 'Alakazam', 'Psíquico', NULL, 1, now()),
  (66, 'Machop', 'Machop', 'Lucha', NULL, 1, now()),
  (67, 'Machoke', 'Machoke', 'Lucha', NULL, 1, now()),
  (68, 'Machamp', 'Machamp', 'Lucha', NULL, 1, now()),
  (69, 'Bellsprout', 'Bellsprout', 'Planta', 'Veneno', 1, now()),
  (70, 'Weepinbell', 'Weepinbell', 'Planta', 'Veneno', 1, now()),
  (71, 'Victreebel', 'Victreebel', 'Planta', 'Veneno', 1, now()),
  (72, 'Tentacool', 'Tentacool', 'Agua', 'Veneno', 1, now()),
  (73, 'Tentacruel', 'Tentacruel', 'Agua', 'Veneno', 1, now()),
  (74, 'Geodude', 'Geodude', 'Roca', 'Tierra', 1, now()),
  (75, 'Graveler', 'Graveler', 'Roca', 'Tierra', 1, now()),
  (76, 'Golem', 'Golem', 'Roca', 'Tierra', 1, now()),
  (77, 'Ponyta', 'Ponyta', 'Fuego', NULL, 1, now()),
  (78, 'Rapidash', 'Rapidash', 'Fuego', NULL, 1, now()),
  (79, 'Slowpoke', 'Slowpoke', 'Agua', 'Psíquico', 1, now()),
  (80, 'Slowbro', 'Slowbro', 'Agua', 'Psíquico', 1, now()),
  (81, 'Magnemite', 'Magnemite', 'Eléctrico', 'Acero', 1, now()),
  (82, 'Magneton', 'Magneton', 'Eléctrico', 'Acero', 1, now()),
  (83, 'Farfetchd', 'Farfetch''d', 'Normal', 'Volador', 1, now()),
  (84, 'Doduo', 'Doduo', 'Normal', 'Volador', 1, now()),
  (85, 'Dodrio', 'Dodrio', 'Normal', 'Volador', 1, now()),
  (86, 'Seel', 'Seel', 'Agua', NULL, 1, now()),
  (87, 'Dewgong', 'Dewgong', 'Agua', 'Hielo', 1, now()),
  (88, 'Grimer', 'Grimer', 'Veneno', NULL, 1, now()),
  (89, 'Muk', 'Muk', 'Veneno', NULL, 1, now()),
  (90, 'Shellder', 'Shellder', 'Agua', NULL, 1, now()),
  (91, 'Cloyster', 'Cloyster', 'Agua', 'Hielo', 1, now()),
  (92, 'Gastly', 'Gastly', 'Fantasma', 'Veneno', 1, now()),
  (93, 'Haunter', 'Haunter', 'Fantasma', 'Veneno', 1, now()),
  (94, 'Gengar', 'Gengar', 'Fantasma', 'Veneno', 1, now()),
  (95, 'Onix', 'Onix', 'Roca', 'Tierra', 1, now()),
  (96, 'Drowzee', 'Drowzee', 'Psíquico', NULL, 1, now()),
  (97, 'Hypno', 'Hypno', 'Psíquico', NULL, 1, now()),
  (98, 'Krabby', 'Krabby', 'Agua', NULL, 1, now()),
  (99, 'Kingler', 'Kingler', 'Agua', 'Acero', 1, now()),
  (100, 'Voltorb', 'Voltorb', 'Eléctrico', NULL, 1, now()),
  (101, 'Electrode', 'Electrode', 'Eléctrico', NULL, 1, now()),
  (102, 'Exeggcute', 'Exeggcute', 'Planta', 'Psíquico', 1, now()),
  (103, 'Exeggutor', 'Exeggutor', 'Planta', 'Psíquico', 1, now()),
  (104, 'Cubone', 'Cubone', 'Tierra', NULL, 1, now()),
  (105, 'Marowak', 'Marowak', 'Tierra', NULL, 1, now()),
  (106, 'Hitmonlee', 'Hitmonlee', 'Lucha', NULL, 1, now()),
  (107, 'Hitmonchan', 'Hitmonchan', 'Lucha', NULL, 1, now()),
  (108, 'Lickitung', 'Lickitung', 'Normal', NULL, 1, now()),
  (109, 'Koffing', 'Koffing', 'Veneno', NULL, 1, now()),
  (110, 'Weezing', 'Weezing', 'Veneno', NULL, 1, now()),
  (111, 'Rhyhorn', 'Rhyhorn', 'Tierra', 'Roca', 1, now()),
  (112, 'Rhydon', 'Rhydon', 'Tierra', 'Roca', 1, now()),
  (113, 'Chansey', 'Chansey', 'Normal', NULL, 1, now()),
  (114, 'Tangela', 'Tangela', 'Planta', NULL, 1, now()),
  (115, 'Kangaskhan', 'Kangaskhan', 'Normal', NULL, 1, now()),
  (116, 'Horsea', 'Horsea', 'Agua', NULL, 1, now()),
  (117, 'Seadra', 'Seadra', 'Agua', NULL, 1, now()),
  (118, 'Goldeen', 'Goldeen', 'Agua', NULL, 1, now()),
  (119, 'Seaking', 'Seaking', 'Agua', NULL, 1, now()),
  (120, 'Staryu', 'Staryu', 'Agua', NULL, 1, now()),
  (121, 'Starmie', 'Starmie', 'Agua', 'Psíquico', 1, now()),
  (122, 'Mr Mime', 'Mr. Mime', 'Psíquico', 'Hada', 1, now()),
  (123, 'Scyther', 'Scyther', 'Bicho', 'Volador', 1, now()),
  (124, 'Jynx', 'Jynx', 'Hielo', 'Psíquico', 1, now()),
  (125, 'Electabuzz', 'Electabuzz', 'Eléctrico', NULL, 1, now()),
  (126, 'Magmar', 'Magmar', 'Fuego', NULL, 1, now()),
  (127, 'Pinsir', 'Pinsir', 'Bicho', NULL, 1, now()),
  (128, 'Tauros', 'Tauros', 'Normal', NULL, 1, now()),
  (129, 'Magikarp', 'Magikarp', 'Agua', NULL, 1, now()),
  (130, 'Gyarados', 'Gyarados', 'Agua', 'Volador', 1, now()),
  (131, 'Lapras', 'Lapras', 'Agua', 'Hielo', 1, now()),
  (132, 'Ditto', 'Ditto', 'Normal', NULL, 1, now()),
  (133, 'Eevee', 'Eevee', 'Normal', NULL, 1, now()),
  (134, 'Vaporeon', 'Vaporeon', 'Agua', NULL, 1, now()),
  (135, 'Jolteon', 'Jolteon', 'Eléctrico', NULL, 1, now()),
  (136, 'Flareon', 'Flareon', 'Fuego', NULL, 1, now()),
  (137, 'Porygon', 'Porygon', 'Normal', NULL, 1, now()),
  (138, 'Omanyte', 'Omanyte', 'Roca', 'Agua', 1, now()),
  (139, 'Omastar', 'Omastar', 'Roca', 'Agua', 1, now()),
  (140, 'Kabuto', 'Kabuto', 'Roca', 'Agua', 1, now()),
  (141, 'Kabutops', 'Kabutops', 'Roca', 'Agua', 1, now()),
  (142, 'Aerodactyl', 'Aerodactyl', 'Roca', 'Volador', 1, now()),
  (143, 'Snorlax', 'Snorlax', 'Normal', NULL, 1, now()),
  (144, 'Articuno', 'Articuno', 'Hielo', 'Volador', 1, now()),
  (145, 'Zapdos', 'Zapdos', 'Eléctrico', 'Volador', 1, now()),
  (146, 'Moltres', 'Moltres', 'Fuego', 'Volador', 1, now()),
  (147, 'Dratini', 'Dratini', 'Dragón', NULL, 1, now()),
  (148, 'Dragonair', 'Dragonair', 'Dragón', NULL, 1, now()),
  (149, 'Dragonite', 'Dragonite', 'Dragón', 'Volador', 1, now()),
  (150, 'Mewtwo', 'Mewtwo', 'Psíquico', NULL, 1, now()),
  (151, 'Mew', 'Mew', 'Psíquico', NULL, 1, now()),
  (152, 'Chikorita', 'Chikorita', 'Planta', NULL, 2, now()),
  (153, 'Bayleef', 'Bayleef', 'Planta', NULL, 2, now()),
  (154, 'Meganium', 'Meganium', 'Planta', 'Hada', 2, now()),
  (155, 'Cyndaquil', 'Cyndaquil', 'Fuego', NULL, 2, now()),
  (156, 'Quilava', 'Quilava', 'Fuego', NULL, 2, now()),
  (157, 'Typhlosion', 'Typhlosion', 'Fuego', 'Tierra', 2, now()),
  (158, 'Totodile', 'Totodile', 'Agua', NULL, 2, now()),
  (159, 'Croconaw', 'Croconaw', 'Agua', NULL, 2, now()),
  (160, 'Feraligatr', 'Feraligatr', 'Agua', 'Dragón', 2, now()),
  (161, 'Sentret', 'Sentret', 'Normal', NULL, 2, now()),
  (162, 'Furret', 'Furret', 'Normal', NULL, 2, now()),
  (163, 'Hoothoot', 'Hoothoot', 'Normal', 'Volador', 2, now()),
  (164, 'Noctowl', 'Noctowl', 'Psíquico', 'Volador', 2, now()),
  (165, 'Ledyba', 'Ledyba', 'Bicho', 'Volador', 2, now()),
  (166, 'Ledian', 'Ledian', 'Bicho', 'Volador', 2, now()),
  (167, 'Spinarak', 'Spinarak', 'Bicho', 'Veneno', 2, now()),
  (168, 'Ariados', 'Ariados', 'Bicho', 'Veneno', 2, now()),
  (169, 'Crobat', 'Crobat', 'Veneno', 'Volador', 2, now()),
  (170, 'Chinchou', 'Chinchou', 'Agua', 'Eléctrico', 2, now()),
  (171, 'Lanturn', 'Lanturn', 'Agua', 'Eléctrico', 2, now()),
  (172, 'Pichu', 'Pichu', 'Eléctrico', NULL, 2, now()),
  (173, 'Cleffa', 'Cleffa', 'Hada', NULL, 2, now()),
  (174, 'Igglybuff', 'Igglybuff', 'Normal', 'Hada', 2, now()),
  (175, 'Togepi', 'Togepi', 'Hada', NULL, 2, now()),
  (176, 'Togetic', 'Togetic', 'Hada', 'Volador', 2, now()),
  (177, 'Natu', 'Natu', 'Psíquico', 'Volador', 2, now()),
  (178, 'Xatu', 'Xatu', 'Psíquico', 'Volador', 2, now()),
  (179, 'Mareep', 'Mareep', 'Eléctrico', NULL, 2, now()),
  (180, 'Flaaffy', 'Flaaffy', 'Eléctrico', NULL, 2, now()),
  (181, 'Ampharos', 'Ampharos', 'Eléctrico', NULL, 2, now()),
  (182, 'Bellossom', 'Bellossom', 'Planta', NULL, 2, now()),
  (183, 'Marill', 'Marill', 'Agua', 'Hada', 2, now()),
  (184, 'Azumarill', 'Azumarill', 'Agua', 'Hada', 2, now()),
  (185, 'Sudowoodo', 'Sudowoodo', 'Roca', NULL, 2, now()),
  (186, 'Politoed', 'Politoed', 'Agua', NULL, 2, now()),
  (187, 'Hoppip', 'Hoppip', 'Planta', 'Volador', 2, now()),
  (188, 'Skiploom', 'Skiploom', 'Planta', 'Volador', 2, now()),
  (189, 'Jumpluff', 'Jumpluff', 'Planta', 'Volador', 2, now()),
  (190, 'Aipom', 'Aipom', 'Normal', NULL, 2, now()),
  (191, 'Sunkern', 'Sunkern', 'Planta', NULL, 2, now()),
  (192, 'Sunflora', 'Sunflora', 'Planta', 'Fuego', 2, now()),
  (193, 'Yanma', 'Yanma', 'Bicho', 'Volador', 2, now()),
  (194, 'Wooper', 'Wooper', 'Agua', 'Tierra', 2, now()),
  (195, 'Quagsire', 'Quagsire', 'Agua', 'Tierra', 2, now()),
  (196, 'Espeon', 'Espeon', 'Psíquico', NULL, 2, now()),
  (197, 'Umbreon', 'Umbreon', 'Siniestro', NULL, 2, now()),
  (198, 'Murkrow', 'Murkrow', 'Siniestro', 'Volador', 2, now()),
  (199, 'Slowking', 'Slowking', 'Agua', 'Psíquico', 2, now()),
  (200, 'Misdreavus', 'Misdreavus', 'Fantasma', NULL, 2, now()),
  (201, 'Unown', 'Unown', 'Psíquico', NULL, 2, now()),
  (202, 'Wobbuffet', 'Wobbuffet', 'Psíquico', NULL, 2, now()),
  (203, 'Girafarig', 'Girafarig', 'Normal', 'Psíquico', 2, now()),
  (204, 'Pineco', 'Pineco', 'Bicho', NULL, 2, now()),
  (205, 'Forretress', 'Forretress', 'Bicho', 'Acero', 2, now()),
  (206, 'Dunsparce', 'Dunsparce', 'Normal', NULL, 2, now()),
  (207, 'Gligar', 'Gligar', 'Tierra', 'Volador', 2, now()),
  (208, 'Steelix', 'Steelix', 'Acero', 'Tierra', 2, now()),
  (209, 'Snubbull', 'Snubbull', 'Hada', NULL, 2, now()),
  (210, 'Granbull', 'Granbull', 'Hada', NULL, 2, now()),
  (211, 'Qwilfish', 'Qwilfish', 'Agua', 'Veneno', 2, now()),
  (212, 'Scizor', 'Scizor', 'Bicho', 'Acero', 2, now()),
  (213, 'Shuckle', 'Shuckle', 'Bicho', 'Roca', 2, now()),
  (214, 'Heracross', 'Heracross', 'Bicho', 'Lucha', 2, now()),
  (215, 'Sneasel', 'Sneasel', 'Siniestro', 'Hielo', 2, now()),
  (216, 'Teddiursa', 'Teddiursa', 'Normal', NULL, 2, now()),
  (217, 'Ursaring', 'Ursaring', 'Normal', NULL, 2, now()),
  (218, 'Slugma', 'Slugma', 'Fuego', NULL, 2, now()),
  (219, 'Magcargo', 'Magcargo', 'Fuego', 'Roca', 2, now()),
  (220, 'Swinub', 'Swinub', 'Hielo', 'Tierra', 2, now()),
  (221, 'Piloswine', 'Piloswine', 'Hielo', 'Tierra', 2, now()),
  (222, 'Corsola', 'Corsola', 'Agua', 'Roca', 2, now()),
  (223, 'Remoraid', 'Remoraid', 'Agua', NULL, 2, now()),
  (224, 'Octillery', 'Octillery', 'Agua', NULL, 2, now()),
  (225, 'Delibird', 'Delibird', 'Hielo', 'Volador', 2, now()),
  (226, 'Mantine', 'Mantine', 'Agua', 'Volador', 2, now()),
  (227, 'Skarmory', 'Skarmory', 'Acero', 'Volador', 2, now()),
  (228, 'Houndour', 'Houndour', 'Siniestro', 'Fuego', 2, now()),
  (229, 'Houndoom', 'Houndoom', 'Siniestro', 'Fuego', 2, now()),
  (230, 'Kingdra', 'Kingdra', 'Agua', 'Dragón', 2, now()),
  (231, 'Phanpy', 'Phanpy', 'Tierra', NULL, 2, now()),
  (232, 'Donphan', 'Donphan', 'Tierra', NULL, 2, now()),
  (233, 'Porygon2', 'Porygon2', 'Normal', NULL, 2, now()),
  (234, 'Stantler', 'Stantler', 'Normal', 'Psíquico', 2, now()),
  (235, 'Smeargle', 'Smeargle', 'Normal', NULL, 2, now()),
  (236, 'Tyrogue', 'Tyrogue', 'Lucha', NULL, 2, now()),
  (237, 'Hitmontop', 'Hitmontop', 'Lucha', NULL, 2, now()),
  (238, 'Smoochum', 'Smoochum', 'Hielo', 'Psíquico', 2, now()),
  (239, 'Elekid', 'Elekid', 'Eléctrico', NULL, 2, now()),
  (240, 'Magby', 'Magby', 'Fuego', NULL, 2, now()),
  (241, 'Miltank', 'Miltank', 'Normal', NULL, 2, now()),
  (242, 'Blissey', 'Blissey', 'Normal', NULL, 2, now()),
  (243, 'Raikou', 'Raikou', 'Eléctrico', NULL, 2, now()),
  (244, 'Entei', 'Entei', 'Fuego', NULL, 2, now()),
  (245, 'Suicune', 'Suicune', 'Agua', NULL, 2, now()),
  (246, 'Larvitar', 'Larvitar', 'Roca', 'Tierra', 2, now()),
  (247, 'Pupitar', 'Pupitar', 'Roca', 'Tierra', 2, now()),
  (248, 'Tyranitar', 'Tyranitar', 'Roca', 'Siniestro', 2, now()),
  (249, 'Lugia', 'Lugia', 'Psíquico', 'Volador', 2, now()),
  (250, 'Ho Oh', 'Ho-Oh', 'Fuego', 'Volador', 2, now()),
  (251, 'Celebi', 'Celebi', 'Psíquico', 'Planta', 2, now()),
  (252, 'Old Unown B', 'Old Unown B', 'Normal', NULL, 3, now()),
  (253, 'Old Unown C', 'Old Unown C', 'Normal', NULL, 3, now()),
  (254, 'Old Unown D', 'Old Unown D', 'Normal', NULL, 3, now()),
  (255, 'Old Unown E', 'Old Unown E', 'Normal', NULL, 3, now()),
  (256, 'Old Unown F', 'Old Unown F', 'Normal', NULL, 3, now()),
  (257, 'Old Unown G', 'Old Unown G', 'Normal', NULL, 3, now()),
  (258, 'Old Unown H', 'Old Unown H', 'Normal', NULL, 3, now()),
  (259, 'Old Unown I', 'Old Unown I', 'Normal', NULL, 3, now()),
  (260, 'Old Unown J', 'Old Unown J', 'Normal', NULL, 3, now()),
  (261, 'Old Unown K', 'Old Unown K', 'Normal', NULL, 3, now()),
  (262, 'Old Unown L', 'Old Unown L', 'Normal', NULL, 3, now()),
  (263, 'Old Unown M', 'Old Unown M', 'Normal', NULL, 3, now()),
  (264, 'Old Unown N', 'Old Unown N', 'Normal', NULL, 3, now()),
  (265, 'Old Unown O', 'Old Unown O', 'Normal', NULL, 3, now()),
  (266, 'Old Unown P', 'Old Unown P', 'Normal', NULL, 3, now()),
  (267, 'Old Unown Q', 'Old Unown Q', 'Normal', NULL, 3, now()),
  (268, 'Old Unown R', 'Old Unown R', 'Normal', NULL, 3, now()),
  (269, 'Old Unown S', 'Old Unown S', 'Normal', NULL, 3, now()),
  (270, 'Old Unown T', 'Old Unown T', 'Normal', NULL, 3, now()),
  (271, 'Old Unown U', 'Old Unown U', 'Normal', NULL, 3, now()),
  (272, 'Old Unown V', 'Old Unown V', 'Normal', NULL, 3, now()),
  (273, 'Old Unown W', 'Old Unown W', 'Normal', NULL, 3, now()),
  (274, 'Old Unown X', 'Old Unown X', 'Normal', NULL, 3, now()),
  (275, 'Old Unown Y', 'Old Unown Y', 'Normal', NULL, 3, now()),
  (276, 'Old Unown Z', 'Old Unown Z', 'Normal', NULL, 3, now()),
  (277, 'Treecko', 'Treecko', 'Planta', NULL, 3, now()),
  (278, 'Grovyle', 'Grovyle', 'Planta', 'Dragón', 3, now()),
  (279, 'Sceptile', 'Sceptile', 'Planta', 'Dragón', 3, now()),
  (280, 'Torchic', 'Torchic', 'Fuego', NULL, 3, now()),
  (281, 'Combusken', 'Combusken', 'Fuego', 'Lucha', 3, now()),
  (282, 'Blaziken', 'Blaziken', 'Fuego', 'Lucha', 3, now()),
  (283, 'Mudkip', 'Mudkip', 'Agua', NULL, 3, now()),
  (284, 'Marshtomp', 'Marshtomp', 'Agua', 'Tierra', 3, now()),
  (285, 'Swampert', 'Swampert', 'Agua', 'Tierra', 3, now()),
  (286, 'Poochyena', 'Poochyena', 'Siniestro', NULL, 3, now()),
  (287, 'Mightyena', 'Mightyena', 'Siniestro', NULL, 3, now()),
  (288, 'Zigzagoon', 'Zigzagoon', 'Normal', NULL, 3, now()),
  (289, 'Linoone', 'Linoone', 'Normal', NULL, 3, now()),
  (290, 'Wurmple', 'Wurmple', 'Bicho', NULL, 3, now()),
  (291, 'Silcoon', 'Silcoon', 'Bicho', NULL, 3, now()),
  (292, 'Beautifly', 'Beautifly', 'Bicho', 'Volador', 3, now()),
  (293, 'Cascoon', 'Cascoon', 'Bicho', NULL, 3, now()),
  (294, 'Dustox', 'Dustox', 'Bicho', 'Veneno', 3, now()),
  (295, 'Lotad', 'Lotad', 'Agua', 'Planta', 3, now()),
  (296, 'Lombre', 'Lombre', 'Agua', 'Planta', 3, now()),
  (297, 'Ludicolo', 'Ludicolo', 'Agua', 'Planta', 3, now()),
  (298, 'Seedot', 'Seedot', 'Planta', NULL, 3, now()),
  (299, 'Nuzleaf', 'Nuzleaf', 'Planta', 'Siniestro', 3, now()),
  (300, 'Shiftry', 'Shiftry', 'Planta', 'Siniestro', 3, now()),
  (301, 'Nincada', 'Nincada', 'Bicho', 'Tierra', 3, now()),
  (302, 'Ninjask', 'Ninjask', 'Bicho', 'Volador', 3, now()),
  (303, 'Shedinja', 'Shedinja', 'Bicho', 'Fantasma', 3, now()),
  (304, 'Taillow', 'Taillow', 'Normal', 'Volador', 3, now()),
  (305, 'Swellow', 'Swellow', 'Normal', 'Volador', 3, now()),
  (306, 'Shroomish', 'Shroomish', 'Planta', NULL, 3, now()),
  (307, 'Breloom', 'Breloom', 'Planta', 'Lucha', 3, now()),
  (308, 'Spinda', 'Spinda', 'Normal', NULL, 3, now()),
  (309, 'Wingull', 'Wingull', 'Agua', 'Volador', 3, now()),
  (310, 'Pelipper', 'Pelipper', 'Agua', 'Volador', 3, now()),
  (311, 'Surskit', 'Surskit', 'Bicho', 'Agua', 3, now()),
  (312, 'Masquerain', 'Masquerain', 'Bicho', 'Agua', 3, now()),
  (313, 'Wailmer', 'Wailmer', 'Agua', NULL, 3, now()),
  (314, 'Wailord', 'Wailord', 'Agua', NULL, 3, now()),
  (315, 'Skitty', 'Skitty', 'Normal', NULL, 3, now()),
  (316, 'Delcatty', 'Delcatty', 'Normal', 'Hada', 3, now()),
  (317, 'Kecleon', 'Kecleon', 'Normal', NULL, 3, now()),
  (318, 'Baltoy', 'Baltoy', 'Tierra', 'Psíquico', 3, now()),
  (319, 'Claydol', 'Claydol', 'Tierra', 'Psíquico', 3, now()),
  (320, 'Nosepass', 'Nosepass', 'Roca', NULL, 3, now()),
  (321, 'Torkoal', 'Torkoal', 'Fuego', NULL, 3, now()),
  (322, 'Sableye', 'Sableye', 'Siniestro', 'Fantasma', 3, now()),
  (323, 'Barboach', 'Barboach', 'Agua', 'Tierra', 3, now()),
  (324, 'Whiscash', 'Whiscash', 'Agua', 'Tierra', 3, now()),
  (325, 'Luvdisc', 'Luvdisc', 'Agua', 'Hada', 3, now()),
  (326, 'Corphish', 'Corphish', 'Agua', NULL, 3, now()),
  (327, 'Crawdaunt', 'Crawdaunt', 'Agua', 'Siniestro', 3, now()),
  (328, 'Feebas', 'Feebas', 'Agua', NULL, 3, now()),
  (329, 'Milotic', 'Milotic', 'Agua', NULL, 3, now()),
  (330, 'Carvanha', 'Carvanha', 'Agua', 'Siniestro', 3, now()),
  (331, 'Sharpedo', 'Sharpedo', 'Agua', 'Siniestro', 3, now()),
  (332, 'Trapinch', 'Trapinch', 'Tierra', NULL, 3, now()),
  (333, 'Vibrava', 'Vibrava', 'Tierra', 'Dragón', 3, now()),
  (334, 'Flygon', 'Flygon', 'Tierra', 'Dragón', 3, now()),
  (335, 'Makuhita', 'Makuhita', 'Lucha', NULL, 3, now()),
  (336, 'Hariyama', 'Hariyama', 'Lucha', NULL, 3, now()),
  (337, 'Electrike', 'Electrike', 'Eléctrico', NULL, 3, now()),
  (338, 'Manectric', 'Manectric', 'Eléctrico', NULL, 3, now()),
  (339, 'Numel', 'Numel', 'Fuego', 'Tierra', 3, now()),
  (340, 'Camerupt', 'Camerupt', 'Fuego', 'Tierra', 3, now()),
  (341, 'Spheal', 'Spheal', 'Hielo', 'Agua', 3, now()),
  (342, 'Sealeo', 'Sealeo', 'Hielo', 'Agua', 3, now()),
  (343, 'Walrein', 'Walrein', 'Hielo', 'Agua', 3, now()),
  (344, 'Cacnea', 'Cacnea', 'Planta', NULL, 3, now()),
  (345, 'Cacturne', 'Cacturne', 'Planta', 'Siniestro', 3, now()),
  (346, 'Snorunt', 'Snorunt', 'Hielo', NULL, 3, now()),
  (347, 'Glalie', 'Glalie', 'Hielo', NULL, 3, now()),
  (348, 'Lunatone', 'Lunatone', 'Roca', 'Psíquico', 3, now()),
  (349, 'Solrock', 'Solrock', 'Roca', 'Psíquico', 3, now()),
  (350, 'Azurill', 'Azurill', 'Normal', 'Hada', 3, now()),
  (351, 'Spoink', 'Spoink', 'Psíquico', NULL, 3, now()),
  (352, 'Grumpig', 'Grumpig', 'Psíquico', NULL, 3, now()),
  (353, 'Plusle', 'Plusle', 'Eléctrico', NULL, 3, now()),
  (354, 'Minun', 'Minun', 'Eléctrico', NULL, 3, now()),
  (355, 'Mawile', 'Mawile', 'Acero', 'Hada', 3, now()),
  (356, 'Meditite', 'Meditite', 'Lucha', 'Psíquico', 3, now()),
  (357, 'Medicham', 'Medicham', 'Lucha', 'Psíquico', 3, now()),
  (358, 'Swablu', 'Swablu', 'Normal', 'Volador', 3, now()),
  (359, 'Altaria', 'Altaria', 'Dragón', 'Volador', 3, now()),
  (360, 'Wynaut', 'Wynaut', 'Psíquico', NULL, 3, now()),
  (361, 'Duskull', 'Duskull', 'Fantasma', NULL, 3, now()),
  (362, 'Dusclops', 'Dusclops', 'Fantasma', NULL, 3, now()),
  (363, 'Roselia', 'Roselia', 'Planta', 'Veneno', 3, now()),
  (364, 'Slakoth', 'Slakoth', 'Normal', NULL, 3, now()),
  (365, 'Vigoroth', 'Vigoroth', 'Normal', NULL, 3, now()),
  (366, 'Slaking', 'Slaking', 'Normal', NULL, 3, now()),
  (367, 'Gulpin', 'Gulpin', 'Veneno', 'Normal', 3, now()),
  (368, 'Swalot', 'Swalot', 'Veneno', 'Normal', 3, now()),
  (369, 'Tropius', 'Tropius', 'Planta', 'Volador', 3, now()),
  (370, 'Whismur', 'Whismur', 'Normal', NULL, 3, now()),
  (371, 'Loudred', 'Loudred', 'Normal', NULL, 3, now()),
  (372, 'Exploud', 'Exploud', 'Normal', NULL, 3, now()),
  (373, 'Clamperl', 'Clamperl', 'Agua', NULL, 3, now()),
  (374, 'Huntail', 'Huntail', 'Agua', NULL, 3, now()),
  (375, 'Gorebyss', 'Gorebyss', 'Agua', NULL, 3, now()),
  (376, 'Absol', 'Absol', 'Siniestro', NULL, 3, now()),
  (377, 'Shuppet', 'Shuppet', 'Fantasma', NULL, 3, now()),
  (378, 'Banette', 'Banette', 'Fantasma', NULL, 3, now()),
  (379, 'Seviper', 'Seviper', 'Veneno', NULL, 3, now()),
  (380, 'Zangoose', 'Zangoose', 'Normal', NULL, 3, now()),
  (381, 'Relicanth', 'Relicanth', 'Agua', 'Roca', 3, now()),
  (382, 'Aron', 'Aron', 'Acero', 'Roca', 3, now()),
  (383, 'Lairon', 'Lairon', 'Acero', 'Roca', 3, now()),
  (384, 'Aggron', 'Aggron', 'Acero', 'Roca', 3, now()),
  (385, 'Castform', 'Castform', 'Normal', NULL, 3, now()),
  (386, 'Volbeat', 'Volbeat', 'Bicho', NULL, 3, now()),
  (387, 'Illumise', 'Illumise', 'Bicho', NULL, 4, now()),
  (388, 'Lileep', 'Lileep', 'Roca', 'Planta', 4, now()),
  (389, 'Cradily', 'Cradily', 'Roca', 'Planta', 4, now()),
  (390, 'Anorith', 'Anorith', 'Roca', 'Bicho', 4, now()),
  (391, 'Armaldo', 'Armaldo', 'Roca', 'Bicho', 4, now()),
  (392, 'Ralts', 'Ralts', 'Psíquico', 'Hada', 4, now()),
  (393, 'Kirlia', 'Kirlia', 'Psíquico', 'Hada', 4, now()),
  (394, 'Gardevoir', 'Gardevoir', 'Psíquico', 'Hada', 4, now()),
  (395, 'Bagon', 'Bagon', 'Dragón', NULL, 4, now()),
  (396, 'Shelgon', 'Shelgon', 'Dragón', NULL, 4, now()),
  (397, 'Salamence', 'Salamence', 'Dragón', 'Volador', 4, now()),
  (398, 'Beldum', 'Beldum', 'Acero', 'Psíquico', 4, now()),
  (399, 'Metang', 'Metang', 'Acero', 'Psíquico', 4, now()),
  (400, 'Metagross', 'Metagross', 'Acero', 'Psíquico', 4, now()),
  (401, 'Regirock', 'Regirock', 'Roca', NULL, 4, now()),
  (402, 'Regice', 'Regice', 'Hielo', NULL, 4, now()),
  (403, 'Registeel', 'Registeel', 'Acero', NULL, 4, now()),
  (404, 'Kyogre', 'Kyogre', 'Agua', NULL, 4, now()),
  (405, 'Groudon', 'Groudon', 'Tierra', NULL, 4, now()),
  (406, 'Rayquaza', 'Rayquaza', 'Dragón', 'Volador', 4, now()),
  (407, 'Latias', 'Latias', 'Dragón', 'Psíquico', 4, now()),
  (408, 'Latios', 'Latios', 'Dragón', 'Psíquico', 4, now()),
  (409, 'Jirachi', 'Jirachi', 'Acero', 'Psíquico', 4, now()),
  (410, 'Deoxys', 'Deoxys', 'Psíquico', NULL, 4, now()),
  (411, 'Chimecho', 'Chimecho', 'Psíquico', NULL, 4, now()),
  (412, 'Ambipom', 'Ambipom', 'Normal', NULL, 4, now()),
  (413, 'Arceus', 'Arceus', 'Normal', NULL, 4, now()),
  (414, 'Bonsly', 'Bonsly', 'Roca', NULL, 4, now()),
  (415, 'Budew', 'Budew', 'Planta', 'Veneno', 4, now()),
  (416, 'Chingling', 'Chingling', 'Psíquico', NULL, 4, now()),
  (417, 'Deoxys Attack', 'Deoxys Attack', 'Psíquico', NULL, 4, now()),
  (418, 'Deoxys Defense', 'Deoxys Defense', 'Psíquico', NULL, 4, now()),
  (419, 'Deoxys Speed', 'Deoxys Speed', 'Psíquico', NULL, 4, now()),
  (420, 'Dusknoir', 'Dusknoir', 'Fantasma', NULL, 4, now()),
  (421, 'Electivire', 'Electivire', 'Eléctrico', 'Lucha', 4, now()),
  (422, 'Froslass', 'Froslass', 'Hielo', 'Fantasma', 4, now()),
  (423, 'Gallade', 'Gallade', 'Psíquico', 'Lucha', 4, now()),
  (424, 'Glaceon', 'Glaceon', 'Hielo', NULL, 4, now()),
  (425, 'Gliscor', 'Gliscor', 'Tierra', 'Volador', 4, now()),
  (426, 'Happiny', 'Happiny', 'Normal', NULL, 4, now()),
  (427, 'Honchkrow', 'Honchkrow', 'Siniestro', 'Volador', 4, now()),
  (428, 'Leafeon', 'Leafeon', 'Planta', NULL, 4, now()),
  (429, 'Lickilicky', 'Lickilicky', 'Normal', NULL, 4, now()),
  (430, 'Magmortar', 'Magmortar', 'Fuego', NULL, 4, now()),
  (431, 'Magnezone', 'Magnezone', 'Eléctrico', 'Acero', 4, now()),
  (432, 'Mamoswine', 'Mamoswine', 'Hielo', 'Tierra', 4, now()),
  (433, 'Mantyke', 'Mantyke', 'Agua', 'Volador', 4, now()),
  (434, 'Mismagius', 'Mismagius', 'Fantasma', NULL, 4, now()),
  (435, 'Mime Jr', 'Mime Jr', 'Psíquico', 'Hada', 4, now()),
  (436, 'Munchlax', 'Munchlax', 'Normal', NULL, 4, now()),
  (437, 'Porygon Z', 'Porygon Z', 'Normal', NULL, 4, now()),
  (438, 'Probopass', 'Probopass', 'Roca', 'Acero', 4, now()),
  (439, 'Regieleki', 'Regieleki', 'Eléctrico', NULL, 4, now()),
  (440, 'Regidrago', 'Regidrago', 'Dragón', NULL, 4, now()),
  (441, 'Regigigas', 'Regigigas', 'Normal', NULL, 4, now()),
  (442, 'Rhyperior', 'Rhyperior', 'Tierra', 'Roca', 4, now()),
  (443, 'Roserade', 'Roserade', 'Planta', 'Veneno', 4, now()),
  (444, 'Sylveon', 'Sylveon', 'Hada', NULL, 4, now()),
  (445, 'Tangrowth', 'Tangrowth', 'Planta', NULL, 4, now()),
  (446, 'Togekiss', 'Togekiss', 'Hada', 'Volador', 4, now()),
  (447, 'Weavile', 'Weavile', 'Siniestro', 'Hielo', 4, now()),
  (448, 'Yanmega', 'Yanmega', 'Bicho', 'Volador', 4, now()),
  (449, 'Annihilape', 'Annihilape', 'Lucha', 'Fantasma', 4, now()),
  (450, 'Farigiraf', 'Farigiraf', 'Normal', 'Psíquico', 4, now()),
  (451, 'Dudunsparce', 'Dudunsparce', 'Normal', NULL, 4, now()),
  (452, 'Wyrdeer', 'Wyrdeer', 'Normal', 'Psíquico', 4, now()),
  (453, 'Ursaluna', 'Ursaluna', 'Tierra', 'Normal', 4, now()),
  (454, 'Ursaluna Bloodmoon', 'Ursaluna (Luna de Sangre)', 'Tierra', 'Normal', 4, now()),
  (455, 'Kleavor', 'Kleavor', 'Bicho', 'Roca', 4, now())
ON CONFLICT (id_interno_gba) DO UPDATE SET
  nombre_es = EXCLUDED.nombre_es,
  tipo_1 = EXCLUDED.tipo_1,
  tipo_2 = EXCLUDED.tipo_2,
  generacion = EXCLUDED.generacion;
