-- EGP - Exchange Global de Pokemon - Seed masivo de 90 empresas
TRUNCATE TABLE public.empresas CASCADE;
TRUNCATE TABLE public.portafolio_usuario CASCADE;
TRUNCATE TABLE public.historial_transacciones CASCADE;

INSERT INTO public.empresas (ticker, nombre, region, sector, ceo_nombre, ceo_sprite, descripcion, precio_base, capitalizacion_mercado, variacion_24h) VALUES
('SLPH','Silph Co.','Kanto','Tecnología','Presidente Silph','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/max-revive.png','Fabricante global de Poké Balls y sistemas de contención Ether.',111.66,37690,-0.99),
('RCKT','Rocket Game Corner','Kanto','Entretenimiento','Giovanni','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/blackglasses.png','Imperio de casinos y tecnología con nexos en el mercado Ether.',77.78,41056,-2.19),
('CINN','Laboratorios Cinnabar','Kanto','Biotecnología','Dr. Blaine','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ether.png','Pioneros en clonación fósil y terapia génica.',228.76,16936,0.8),
('KPOW','Red Eléctrica Kanto','Kanto','Energía','Lt. Surge','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/thunder-stone.png','Central eléctrica que abastece a toda la región Kanto.',372.56,14521,1.96),
('PEWT','Corp. Minera Pewter','Kanto','Minería','Brock','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/hard-stone.png','Extracción de minerales raros y piedras evolutivas.',153.06,67376,-5.37),
('CELD','Grandes Almacenes Celadon','Kanto','Comercio','Erika','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rage-candy-bar.png','Cadena minorista más grande de Kanto.',337.45,92249,-2.95),
('SAFF','Dojo Saffron','Kanto','Entrenamiento','Maestro Kiyo','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/focus-band.png','Gimnasio de élite que entrena a futuros Campeones.',83.84,63962,1.64),
('CERU','Acuario Cerulean','Kanto','Turismo','Misty','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sea-incense.png','Acuario con 2M de visitantes al año.',40.11,15325,-1.22),
('PALL','Rancho Pallet','Kanto','Agricultura','Prof. Oak','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/berry-juice.png','Centro de investigación de razas y bayas.',125.6,67991,-2.16),
('VIRI','Silvicultura Verde','Kanto','Forestal','Gardener','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/leaf-stone.png','Gestión sostenible de bosques protegidos.',367.63,60010,-3.37),
('FUCH','Safari Zone Fuchsia','Kanto','Turismo','Guardabosques','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/safari-ball.png','Reserva natural de especies exóticas.',268.55,77605,2.87),
('NUGG','Puerto Nugget','Kanto','Transporte','Marino','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sea-incense.png','Puerto comercial que conecta Kanto con Johto.',365.63,94924,1.81),
('DIGT','Túnel Digital','Kanto','Tecnología','Ing. Silph','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/up-grade.png','Desarrollo de software para dispositivos Ether.',308.68,72508,3.03),
('MAGN','Planta Magnética','Kanto','Energía','Científico','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/magnet.png','Generación de energía limpia por inducción.',320.08,58773,1.5),
('CYCL','Ruta Ciclista','Kanto','Transporte','Rydel','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mach-bike.png','Red de bicicletas y movilidad eléctrica.',134.83,61756,-5.44),
('TOKI','Torre Pokémon','Kanto','Inmobiliario','Ejecutivo','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/up-grade.png','Desarrollo de infraestructura urbana.',256.36,77442,3.5),
('CARN','Parque de Atracciones','Kanto','Entretenimiento','Animador','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rage-candy-bar.png','Parque temático con atracciones Ether.',389.21,98835,1.71),
('FARM','Granja Berry','Kanto','Agricultura','Cultivador','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rawst-berry.png','Producción masiva de berries medicinales.',356.5,62888,-3.12),
('LABO','Laboratorio Lavender','Kanto','Ciencia','Científico','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ether.png','Investigación en comunicación espiritual y Ether.',114,40860,-4.63),
('POKE','Centro Pokémon','Kanto','Salud','Enfermera Joy','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/heal-powder.png','Red de centros de salud para Pokémon.',310.77,20716,0.42),
('GYMA','Liga Pokémon','Kanto','Deportes','Campeón','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/expert-belt.png','Organización oficial de torneos regionales.',48.16,42476,-5.85),
('REPU','Tienda de Repelentes','Kanto','Manufactura','Ingeniero','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/max-repel.png','Líder en sistemas de defensa personal.',156.1,57388,-1.51),
('BICI','Fábrica de Bicicletas','Kanto','Manufactura','Mecánico','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mach-bike.png','Producción de bicicletas de montaña.',236.3,18371,3.94),
('PESK','Club de Pesca','Kanto','Pesca','Pescador','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/old-rod.png','Flota pesquera con permisos especiales.',145.61,14849,-4.27),
('CARA','Canning & Caracol','Kanto','Alimentos','Chef','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rage-candy-bar.png','Enlatados y conservas de la región.',191.87,12954,-0.42),
('VIVI','Vivero Ciudad','Kanto','Jardinería','Jardinero','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/leaf-stone.png','Vivero oficial de la Liga.',338.98,61548,-5.68),
('MUSE','Museo de la Ciencia','Kanto','Cultura','Director','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/odd-keystone.png','Museo interactivo de tecnología Pokémon.',372.51,47989,3.63),
('RADI','Torre Radio','Kanto','Medios','Directora','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/wide-lens.png','Primera emisora radial de Kanto.',321.38,23343,-2.33),
('AERO','Aerolíneas Kanto','Kanto','Transporte','Piloto','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fly-fossil.png','Conexiones aéreas entre todas las regiones.',78.16,62643,0.57),
('FERI','Ferrocarril Kantuno','Kanto','Transporte','Ingeniero','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mach-bike.png','Red ferroviaria de superficie.',276.74,68422,-5.8),
('RADT','Torre Radio Goldenrod','Johto','Medios','DJ Mary','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/wide-lens.png','La voz de Johto. Radio, TV y streaming.',124.87,76857,-3.86),
('MOMO','Granja Mu-Mu','Johto','Agricultura','Granjero Baoba','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/moomoo-milk.png','Leche Mu-Mu, el estándar de calidad.',245.14,59460,2.74),
('KURT','Artesanías Kurt','Johto','Lujo','Kurt','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lure-ball.png','Apricornas de colección. Cada pieza única.',27.73,44157,-4.34),
('MAGT','Magnet Train','Johto','Logística','Copión','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mach-bike.png','Tren bala que conecta Kanto y Johto.',100.76,29348,-1.3),
('OLIV','Puerto Olivo','Johto','Transporte','Capitán','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sea-incense.png','Puerto principal de Johto.',145.88,91422,5.7),
('LAGO','Resort Lago Caracol','Johto','Turismo','Claire','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/water-stone.png','Complejo turístico con Gyarados rojos.',245.82,64177,-1.98),
('TORR','Torre Bellsprout','Johto','Patrimonio','Anciano Li','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/old-rod.png','Preservación de linajes antiguos.',284.71,87044,-0.83),
('RUIN','Ruinas Alpha','Johto','Arqueología','Prof. Maple','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/odd-keystone.png','Desciframiento de los Unown.',193.2,59374,4.71),
('BATL','Frente de Batalla','Johto','Entretenimiento','Palmer','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/expert-belt.png','Estadio internacional de batallas.',202.29,33073,2.15),
('DRGN','Cueva Dragón','Johto','Cría','Claire','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dragon-scale.png','Santuario de dragones en Ciudad Endrino.',382.2,54490,-1.91),
('FLOR','Floristería Azalea','Johto','Jardinería','Bella','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/floral-mail.png','Cultivo de flores para perfumes.',388.29,96732,5.26),
('CIEN','Mt. Silver Lab','Johto','Ciencia','Científico','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ether.png','Investigación en rutas migratorias.',297.03,87060,3),
('BOSQ','Bosque Azalea','Johto','Forestal','Leñador','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/hard-stone.png','Explotación sostenible de madera.',39.59,19250,0.32),
('APRI','Apricornas del Sur','Johto','Agricultura','Cultivador','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lure-ball.png','Cosecha de Apricornas silvestres.',237.05,47230,-4.35),
('BALN','Balneario Ciudad Olivo','Johto','Turismo','Recepcionista','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/heal-powder.png','Aguas termales con propiedades curativas.',234,69090,3.22),
('HIEL','Túnel Helado','Johto','Minería','Minero','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/hard-stone.png','Extracción de hielo eterno.',98.94,44504,3.53),
('TORE','Torre Mental','Johto','Cultura','Sabio','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/odd-keystone.png','Centro de meditación y artes Ether.',25.36,55454,-0.77),
('CRIA','Centro de Cría','Johto','Cría','Hana','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/soothe-bell.png','Guardería de Pokémon de élite.',38.85,14987,-2.54),
('MARZ','Marztrail','Johto','Turismo','Guía','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sea-incense.png','Excursiones por la ruta 38.',409.52,72301,4.26),
('CAMP','Campamento del Bosque','Johto','Turismo','Monitor','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/poke-ball.png','Campamentos de verano para entrenadores.',342.61,72085,3.24),
('GRAN','Granja de Miltank','Johto','Agricultura','Granjero','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/moomoo-milk.png','Producción artesanal de queso.',66.96,93365,4.96),
('MALA','Maletero Viajero','Johto','Logística','Repartidor','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mach-bike.png','Red de mensajería regional.',257.19,82454,-0.38),
('FARI','Faro de Ciudad Olivo','Johto','Energía','Jefe','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/thunder-stone.png','Faro alimentado por Ampharos.',98.71,27946,1.98),
('PUZO','Templo Ho-Oh','Johto','Patrimonio','Sumo Sacerdote','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sacred-ash.png','Santuario del ave legendaria.',379.11,44542,2.81),
('GLAC','Ruta del Glaciar','Johto','Turismo','Guía','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ice-heal.png','Excursiones al monte Plateado.',294.41,80285,0.08),
('TERM','Termal Santuario','Johto','Salud','Médico','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/heal-powder.png','Centro de rehabilitación con aguas termales.',396.1,90800,4.9),
('CASC','Cascada Tohjo','Johto','Turismo','Naturalista','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sea-incense.png','Observatorio de aves migratorias.',321.85,67696,-2.7),
('PUER','Puerto Bonito','Johto','Transporte','Marinero','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sea-incense.png','Ferry entre Johto y Hoenn.',316.42,18077,-4.22),
('GOLD','Centro Comercial','Johto','Comercio','Gerente','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/coin.png','Tienda departamental de Ciudad Trigal.',344.02,30163,-0.27),
('NEGR','Mercado Negro','Johto','Comercio','Comerciante','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/blackglasses.png','Mercado de objetos raros.',357.74,50395,-4.9),
('DVON','Devon Corp.','Hoenn','Tecnología','Sr. Peñas','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/devon-parts.png','Nanotecnología y restauración fósil.',145.96,64403,-5.33),
('STER','Astilleros Stern','Hoenn','Transporte','Capitán Stern','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sail-fossil.png','Astilleros de Ciudad Portual.',122.94,45596,-4.6),
('MAUV','Centro Mauville','Hoenn','Comercio','Wattson','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/magnet.png','Complejo comercial autosuficiente.',211.26,12456,1.23),
('CLIM','Instituto Clima','Hoenn','Clima','Dr. Storm','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/damp-rock.png','Predicción meteorológica global.',194.54,16797,4.76),
('RUST','Mina Rustboro','Hoenn','Minería','Trabajador','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/hard-stone.png','Materiales para construcción regional.',380.67,52289,3.27),
('SLAT','Mercado Portual','Hoenn','Comercio','Secretario','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/coin.png','Punto de encuentro de traders.',105.47,74231,4.44),
('FALL','Rancho Fallarbor','Hoenn','Agricultura','Rancho','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rawst-berry.png','Crianza de tipo tierra y fuego.',135.07,96603,1.56),
('LAVA','Balneario Lavaridge','Hoenn','Energía','Flannery','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/charcoal.png','Energía geotérmica y turismo termal.',70.94,55963,-2.48),
('PACF','Pesca Pacifidlog','Hoenn','Pesca','Pescador','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/old-rod.png','Captura de especies raras.',71.03,13540,-2.94),
('EVLG','Liga Ever Grande','Hoenn','Deportes','Campeón Wallace','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/water-stone.png','Sede de la Liga Hoenn.',285.45,43075,-5.43),
('SINN','Laboratorio Sinnoh','Hoenn','Tecnología','Científico','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ether.png','Desarrollo de tecnología de almacenamiento.',361.45,85095,1.63),
('BOSC','Bosque Petrificado','Hoenn','Forestal','Guardabosques','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/leaf-stone.png','Reserva de fósiles vivientes.',104.41,50862,3.82),
('DESC','Desierto del Safari','Hoenn','Turismo','Guardia','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/safari-ball.png','Recorridos en buggy por el desierto.',200.22,67111,-2.56),
('PLAY','Playa Clampeona','Hoenn','Turismo','Salvavidas','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sea-incense.png','Complejo vacacional en la playa.',381.09,90778,2.19),
('CUEV','Cueva Granito','Hoenn','Minería','Minero','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/hard-stone.png','Extracción de granito regional.',294.06,80973,2.5),
('VOLC','Observatorio Volcán','Hoenn','Ciencia','Vulcanólogo','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fire-stone.png','Monitoreo de la actividad volcánica.',190.9,96820,-0.55),
('TROP','Isla Trovita','Hoenn','Turismo','Guía','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/leaf-stone.png','Ecoturismo en la jungla.',342.19,50834,3.47),
('ESCO','Escuela de Entrenadores','Hoenn','Educación','Director','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/expert-belt.png','Academia oficial de entrenadores.',141.27,88384,-1.11),
('CENT','Centro Espacial','Hoenn','Tecnología','Científico','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/clear-bell.png','Investigación de ondas Ether desde el espacio.',252.67,15746,-0.91),
('BATT','Fábrica Batalla','Hoenn','Entretenimiento','Director','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/expert-belt.png','Fábrica de alquiler de Pokémon.',190.13,64055,-4.48),
('PALC','Palacio Batalla','Hoenn','Entretenimiento','Aristócrata','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/quick-claw.png','Torneos exclusivos para nobles.',94.08,37509,-0.9),
('DOMO','Cúpula Batalla','Hoenn','Entretenimiento','Organizador','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/expert-belt.png','Estadio de dobles profesional.',376.45,27514,3.26),
('PIRA','Pirámide Batalla','Hoenn','Entretenimiento','Faraón','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/hard-stone.png','Desafíos en la pirámide.',160.17,82376,-4.4),
('MANA','Mansión Pokémon','Hoenn','Turismo','Mayordomo','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tea.png','Recorridos por la mansión encantada.',288.83,79813,-2.58),
('CAÑO','Cañón Metálico','Hoenn','Minería','Minero','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/hard-stone.png','Extracción de metales raros.',102.95,79427,-5.45),
('VALLE','Valle Safári','Hoenn','Turismo','Guardabosques','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/safari-ball.png','Recorridos en globo.',367.8,33224,-2.57),
('ISLA','Isla Sur','Hoenn','Pesca','Pescador','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/old-rod.png','Pesca de altura.',339.33,23286,-1.49);

-- Historial de precios simulados
INSERT INTO public.historial_precios (empresa_id, precio, registrado_en)
SELECT e.id, e.precio_base, now() - interval '1 hour'
FROM public.empresas e;
